/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_ERROR = 'USER_LOADED_ERROR';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

/* admins */
export const ADMINS_LIST_GET_LIST = 'ADMINS_LIST_GET_LIST';
export const ADMINS_LIST_GET_LIST_SUCCESS = 'ADMINS_LIST_GET_LIST_SUCCESS';
export const ADMINS_LIST_GET_LIST_ERROR = 'ADMINS_LIST_GET_LIST_ERROR';
export const ADMINS_LIST_GET_LIST_WITH_FILTER =
  'ADMINS_LIST_GET_LIST_WITH_FILTER';
export const ADMINS_LIST_GET_LIST_WITH_ORDER =
  'ADMINS_LIST_GET_LIST_WITH_ORDER';
export const ADMINS_LIST_GET_LIST_SEARCH = 'ADMINS_LIST_GET_LIST_SEARCH';
export const ADMINS_LIST_ADD_ITEM = 'ADMINS_LIST_ADD_ITEM';
export const ADMINS_LIST_ADD_ITEM_SUCCESS = 'ADMINS_LIST_ADD_ITEM_SUCCESS';
export const ADMINS_LIST_ADD_ITEM_ERROR = 'ADMINS_LIST_ADD_ITEM_ERROR';
export const ADMINS_LIST_DELETE_ITEM = 'ADMINS_LIST_DELETE_ITEM';
export const ADMINS_LIST_DELETE_ITEM_SUCCESS =
  'ADMINS_LIST_DELETE_ITEM_SUCCESS';
export const ADMINS_LIST_SELECTED_ITEMS_CHANGE =
  'ADMINS_LIST_SELECTED_ITEMS_CHANGE';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

/* FACULTIES */
export const FACULTIES_LIST_GET_LIST = 'FACULTIES_LIST_GET_LIST';
export const FACULTIES_LIST_GET_LIST_SUCCESS =
  'FACULTIES_LIST_GET_LIST_SUCCESS';
export const FACULTIES_LIST_GET_LIST_ERROR = 'FACULTIES_LIST_GET_LIST_ERROR';
export const FACULTIES_LIST_GET_LIST_WITH_FILTER =
  'FACULTIES_LIST_GET_LIST_WITH_FILTER';
export const FACULTIES_LIST_GET_LIST_WITH_ORDER =
  'FACULTIES_LIST_GET_LIST_WITH_ORDER';
export const FACULTIES_LIST_GET_LIST_SEARCH = 'FACULTIES_LIST_GET_LIST_SEARCH';
export const FACULTIES_LIST_ADD_ITEM = 'FACULTIES_LIST_ADD_ITEM';
export const FACULTIES_LIST_ADD_ITEM_SUCCESS =
  'FACULTIES_LIST_ADD_ITEM_SUCCESS';
export const FACULTIES_LIST_ADD_ITEM_ERROR = 'FACULTIES_LIST_ADD_ITEM_ERROR';
export const FACULTIES_LIST_UPDATE_ITEM = 'FACULTIES_LIST_UPDATE_ITEM';
export const FACULTIES_LIST_UPDATE_ITEM_SUCCESS =
  'FACULTIES_LIST_UPDATE_ITEM_SUCCESS';
export const FACULTIES_LIST_UPDATE_ITEM_ERROR =
  'FACULTIES_LIST_UPDATE_ITEM_ERROR';
export const FACULTIES_LIST_SELECTED_ITEMS_CHANGE =
  'FACULTIES_LIST_SELECTED_ITEMS_CHANGE';
export const FACULTIES_LIST_GET_LIST_WITH_TWO_FILTER =
  'FACULTIES_LIST_GET_LIST_WITH_TWO_FILTER';

/* Faculty Details */
export const FACULTY_GET_DETAILS = 'FACULTY_GET_DETAILS';
export const FACULTY_GET_DETAILS_SUCCESS = 'FACULTY_GET_DETAILS_SUCCESS';
export const FACULTY_GET_DETAILS_ERROR = 'FACULTY_GET_DETAILS';

/* NEWS */
export const NEWS_LIST_GET_LIST = 'NEWS_LIST_GET_LIST';
export const NEWS_LIST_GET_LIST_SUCCESS = 'NEWS_LIST_GET_LIST_SUCCESS';
export const NEWS_LIST_GET_LIST_ERROR = 'NEWS_LIST_GET_LIST_ERROR';
export const NEWS_LIST_GET_LIST_WITH_FILTER = 'NEWS_LIST_GET_LIST_WITH_FILTER';
export const NEWS_LIST_GET_LIST_WITH_ORDER = 'NEWS_LIST_GET_LIST_WITH_ORDER';
export const NEWS_LIST_GET_LIST_SEARCH = 'NEWS_LIST_GET_LIST_SEARCH';
export const NEWS_LIST_ADD_ITEM = 'NEWS_LIST_ADD_ITEM';
export const NEWS_LIST_ADD_ITEM_SUCCESS = 'NEWS_LIST_ADD_ITEM_SUCCESS';
export const NEWS_LIST_ADD_ITEM_ERROR = 'NEWS_LIST_ADD_ITEM_ERROR';
export const NEWS_LIST_UPDATE_ITEM = 'NEWS_LIST_UPDATE_ITEM';
export const NEWS_LIST_UPDATE_ITEM_SUCCESS = 'NEWS_LIST_UPDATE_ITEM_SUCCESS';
export const NEWS_LIST_UPDATE_ITEM_ERROR = 'NEWS_LIST_UPDATE_ITEM_ERROR';
export const NEWS_LIST_DELETE_ITEM = 'NEWS_LIST_DELETE_ITEM';
export const NEWS_LIST_DELETE_ITEM_SUCCESS = 'NEWS_LIST_DELETE_ITEM_SUCCESS';
export const NEWS_LIST_DELETE_ITEM_ERROR = 'NEWS_LIST_DELETE_ITEM_ERROR';
export const NEWS_LIST_SELECTED_ITEMS_CHANGE =
  'NEWS_LIST_SELECTED_ITEMS_CHANGE';
export const NEWS_LIST_GET_LIST_WITH_TWO_FILTER =
  'NEWS_LIST_GET_LIST_WITH_TWO_FILTER';
export const NEWS_LIST_GET_LIST_BY_TRACKING = 'NEWS_LIST_GET_LIST_BY_TRACKING';
export const NEWS_LIST_GET_LIST_BY_TRACKING_SUCCESS =
  'NEWS_LIST_GET_LIST_BY_TRACKING_SUCCESS';
export const NEWS_LIST_GET_LIST_BY_TRACKING_ERROR =
  'NEWS_LIST_GET_LIST_BY_TRACKING_ERROR';

/* ADVS */
export const ADVS_LIST_GET_LIST = 'ADVS_LIST_GET_LIST';
export const ADVS_LIST_GET_LIST_SUCCESS = 'ADVS_LIST_GET_LIST_SUCCESS';
export const ADVS_LIST_GET_LIST_ERROR = 'ADVS_LIST_GET_LIST_ERROR';
export const ADVS_LIST_GET_LIST_WITH_FILTER = 'ADVS_LIST_GET_LIST_WITH_FILTER';
export const ADVS_LIST_GET_LIST_WITH_ORDER = 'ADVS_LIST_GET_LIST_WITH_ORDER';
export const ADVS_LIST_GET_LIST_SEARCH = 'ADVS_LIST_GET_LIST_SEARCH';
export const ADVS_LIST_ADD_ITEM = 'ADVS_LIST_ADD_ITEM';
export const ADVS_LIST_ADD_ITEM_SUCCESS = 'ADVS_LIST_ADD_ITEM_SUCCESS';
export const ADVS_LIST_ADD_ITEM_ERROR = 'ADVS_LIST_ADD_ITEM_ERROR';
export const ADVS_LIST_UPDATE_ITEM = 'ADVS_LIST_UPDATE_ITEM';
export const ADVS_LIST_UPDATE_ITEM_SUCCESS = 'ADVS_LIST_UPDATE_ITEM_SUCCESS';
export const ADVS_LIST_UPDATE_ITEM_ERROR = 'ADVS_LIST_UPDATE_ITEM_ERROR';
export const ADVS_LIST_DELETE_ITEM = 'ADVS_LIST_DELETE_ITEM';
export const ADVS_LIST_DELETE_ITEM_SUCCESS = 'ADVS_LIST_DELETE_ITEM_SUCCESS';
export const ADVS_LIST_DELETE_ITEM_ERROR = 'ADVS_LIST_DELETE_ITEM_ERROR';
export const ADVS_LIST_SELECTED_ITEMS_CHANGE =
  'ADVS_LIST_SELECTED_ITEMS_CHANGE';
export const ADVS_LIST_GET_LIST_WITH_TWO_FILTER =
  'ADVS_LIST_GET_LIST_WITH_TWO_FILTER';
export const ADVS_LIST_GET_LIST_BY_TRACKING = 'ADVS_LIST_GET_LIST_BY_TRACKING';
export const ADVS_LIST_GET_LIST_BY_TRACKING_SUCCESS =
  'ADVS_LIST_GET_LIST_BY_TRACKING_SUCCESS';
export const ADVS_LIST_GET_LIST_BY_TRACKING_ERROR =
  'ADVS_LIST_GET_LIST_BY_TRACKING_ERROR';

/* FILES */
export const FILES_GET_LIST = 'FILES_GET_LIST';
export const FILES_GET_LIST_SUCCESS = 'FILES_GET_LIST_SUCCESS';
export const FILES_GET_LIST_ERROR = 'FILES_GET_LIST_ERROR';
export const FILES_ADD_ITEM = 'FILES_ADD_ITEM';
export const FILES_ADD_ITEM_SUCCESS = 'FILES_ADD_ITEM_SUCCESS';
export const FILES_ADD_ITEM_ERROR = 'FILES_ADD_ITEM_ERROR';
export const FILES_DELETE_ITEM = 'FILES_DELETE_ITEM';
export const FILES_DELETE_ITEM_SUCCESS = 'FILES_DELETE_ITEM_SUCCESS';
export const FILES_DELETE_ITEM_ERROR = 'FILES_DELETE_ITEM_ERROR';

/* FILES */
export const DEPARTMENTS_LIST_GET_LIST = 'DEPARTMENTS_LIST_GET_LIST';
export const DEPARTMENTS_LIST_GET_LIST_SUCCESS =
  'DEPARTMENTS_LIST_GET_LIST_SUCCESS';
export const DEPARTMENTS_LIST_GET_LIST_ERROR =
  'DEPARTMENTS_LIST_GET_LIST_ERROR';
export const DEPARTMENTS_LIST_GET_LIST_WITH_FILTER =
  'DEPARTMENTS_LIST_GET_LIST_WITH_FILTER';
export const DEPARTMENTS_LIST_GET_LIST_WITH_ORDER =
  'DEPARTMENTS_LIST_GET_LIST_WITH_ORDER';
export const DEPARTMENTS_LIST_GET_LIST_SEARCH =
  'DEPARTMENTS_LIST_GET_LIST_SEARCH';
export const DEPARTMENTS_LIST_ADD_ITEM = 'DEPARTMENTS_LIST_ADD_ITEM';
export const DEPARTMENTS_LIST_ADD_ITEM_SUCCESS =
  'DEPARTMENTS_LIST_ADD_ITEM_SUCCESS';
export const DEPARTMENTS_LIST_ADD_ITEM_ERROR =
  'DEPARTMENTS_LIST_ADD_ITEM_ERROR';
export const DEPARTMENTS_LIST_UPDATE_ITEM = 'DEPARTMENTS_LIST_UPDATE_ITEM';
export const DEPARTMENTS_LIST_UPDATE_ITEM_SUCCESS =
  'DEPARTMENTS_LIST_UPDATE_ITEM_SUCCESS';
export const DEPARTMENTS_LIST_UPDATE_ITEM_ERROR =
  'DEPARTMENTS_LIST_UPDATE_ITEM_ERROR';
export const DEPARTMENTS_LIST_SELECTED_ITEMS_CHANGE =
  'DEPARTMENTS_LIST_SELECTED_ITEMS_CHANGE';
export const DEPARTMENTS_LIST_GET_LIST_WITH_TWO_FILTER =
  'DEPARTMENTS_LIST_GET_LIST_WITH_TWO_FILTER';

/* TODOAPP */
export const TODO_GET_LIST = 'TODO_GET_LIST';
export const TODO_GET_LIST_SUCCESS = 'TODO_GET_LIST_SUCCESS';
export const TODO_GET_LIST_ERROR = 'TODO_GET_LIST_ERROR';
export const TODO_GET_LIST_WITH_FILTER = 'TODO_GET_LIST_WITH_FILTER';
export const TODO_GET_LIST_WITH_ORDER = 'TODO_GET_LIST_WITH_ORDER';
export const TODO_GET_LIST_SEARCH = 'TODO_GET_LIST_SEARCH';
export const TODO_ADD_ITEM = 'TODO_ADD_ITEM';
export const TODO_ADD_ITEM_SUCCESS = 'TODO_ADD_ITEM_SUCCESS';
export const TODO_ADD_ITEM_ERROR = 'TODO_ADD_ITEM_ERROR';
export const TODO_SELECTED_ITEMS_CHANGE = 'TODO_SELECTED_ITEMS_CHANGE';

/* CHAT APP */
export const CHAT_GET_CONTACTS = 'CHAT_GET_CONTACTS';
export const CHAT_GET_CONTACTS_SUCCESS = 'CHAT_GET_CONTACTS_SUCCESS';
export const CHAT_GET_CONTACTS_ERROR = 'CHAT_GET_CONTACTS_ERROR';
export const CHAT_GET_CONVERSATIONS = 'CHAT_GET_CONVERSATIONS';
export const CHAT_GET_CONVERSATIONS_SUCCESS = 'CHAT_GET_CONVERSATIONS_SUCCESS';
export const CHAT_GET_CONVERSATIONS_ERROR = 'CHAT_GET_CONVERSATIONS_ERROR';
export const CHAT_ADD_MESSAGE_TO_CONVERSATION =
  'CHAT_ADD_MESSAGE_TO_CONVERSATION';
export const CHAT_CREATE_CONVERSATION = 'CHAT_CREATE_CONVERSATION';
export const CHAT_SEARCH_CONTACT = 'CHAT_SEARCH_CONTACT';
export const CHAT_CHANGE_CONVERSATION = 'CHAT_CHANGE_CONVERSATION';

/* SURVEY LIST APP */
export const SURVEY_LIST_GET_LIST = 'SURVEY_LIST_GET_LIST';
export const SURVEY_LIST_GET_LIST_SUCCESS = 'SURVEY_LIST_GET_LIST_SUCCESS';
export const SURVEY_LIST_GET_LIST_ERROR = 'SURVEY_LIST_GET_LIST_ERROR';
export const SURVEY_LIST_GET_LIST_WITH_FILTER =
  'SURVEY_LIST_GET_LIST_WITH_FILTER';
export const SURVEY_LIST_GET_LIST_WITH_ORDER =
  'SURVEY_LIST_GET_LIST_WITH_ORDER';
export const SURVEY_LIST_GET_LIST_SEARCH = 'SURVEY_LIST_GET_LIST_SEARCH';
export const SURVEY_LIST_ADD_ITEM = 'SURVEY_LIST_ADD_ITEM';
export const SURVEY_LIST_ADD_ITEM_SUCCESS = 'SURVEY_LIST_ADD_ITEM_SUCCESS';
export const SURVEY_LIST_ADD_ITEM_ERROR = 'SURVEY_LIST_ADD_ITEM_ERROR';
export const SURVEY_LIST_SELECTED_ITEMS_CHANGE =
  'SURVEY_LIST_SELECTED_ITEMS_CHANGE';

/* SURVEY DETAIL APP */
export const SURVEY_GET_DETAILS = 'SURVEY_GET_DETAILS';
export const SURVEY_GET_DETAILS_SUCCESS = 'SURVEY_GET_DETAILS_SUCCESS';
export const SURVEY_GET_DETAILS_ERROR = 'SURVEY_GET_DETAILS_ERROR';
export const SURVEY_DELETE_QUESTION = 'SURVEY_DELETE_QUESTION';
export const SURVEY_SAVE = 'SURVEY_SAVE';
